version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  app:
    image: python:3.9
    container_name: fibonacci_app
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "app.py"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379